// ── Les fonctions acceptées par Salesforce, et le département de chacune ──
// Copie de la liste du sélecteur « Fonction » du site ayming.fr (balise GTM « Enrichment -
// Fonction picker »). Salesforce refuse un lead dont la fonction n'y figure pas (règle VR01),
// d'où une liste fermée plutôt qu'un champ libre. À resynchroniser si le site change la sienne.
// La valeur part vers Pardot en `position`, le département en `departement`.

export var POSITIONS = {
  "Acheteur": "Procurement",
  "Adjoint Administratif Hospitalier": "Departement Information Medicale",
  "Adjoint des Cadres aux Finances": "Departement Information Medicale",
  "Adjoint DRH": "HR",
  "Administrateur": "Executive Management",
  "Agent Comptable": "Finance",
  "Agent Comptable adjoint": "Finance",
  "Asset Manager": "Real Estate",
  "Assistant": null,
  "Assistant DAF": "Finance",
  "Assistant de Direction": "Executive Management",
  "Assistant DFI": "Finance",
  "Assistant Juridique": "Legal",
  "Assistant RH": "HR",
  "Chargé de la Formation": "HR",
  "Chef Comptable": "Finance",
  "Chef de département": "Service Public",
  "Chef de Projet": "Innovation",
  "Chef de projet RH": "HR",
  "Chef de service": "Departement Information Medicale",
  "Chercheur": "Innovation",
  "Comptable": "Finance",
  "Conseiller Juridique": "Legal",
  "Contrôleur de Gestion": "Finance",
  "Contrôleur de Gestion Sociale": "HR",
  "Coordinateur": "Innovation",
  "Crédit Bailleur": "Real Estate",
  "Credit Manager": "Finance",
  "Délégué Régional": "Service Public",
  "Directeur Adjoint": "Executive Management",
  "Directeur Adjoint des Achats": "Procurement",
  "Directeur Administratif": "Executive Management",
  "Directeur Administratif Comptable": "Finance",
  "Directeur Administratif et Financier": "Finance",
  "Directeur Administratif Financier Adjoint": "Finance",
  "Directeur Administratif Juridique": "Legal",
  "Directeur Affaires Etrangères": "Executive Management",
  "Directeur Assurances": "Legal",
  "Directeur Commercial": "Sales & Marketing",
  "Directeur Commercial Marketing": "Sales & Marketing",
  "Directeur Comptable": "Finance",
  "Directeur Contrôle de Gestion": "Finance",
  "Directeur d'Agence": "Executive Management",
  "Directeur d'Environnement": "Facilities",
  "Directeur d'Etablissement": "Executive Management",
  "Directeur d'Exploitation": "Operations",
  "Directeur d'Usine": "Executive Management",
  "Directeur de Cabinet": "Service Public",
  "Directeur de Filiale": "Executive Management",
  "Directeur de Laboratoire": "Innovation",
  "Directeur de la Commande publique": "Service Public",
  "Directeur de la Communication": "Sales & Marketing",
  "Directeur de la Gestion Immobilière": "Real Estate",
  "Directeur de la Gestion Locative": "Real Estate",
  "Directeur de la Promotion Immobilière": "Real Estate",
  "Directeur Délégué": "Executive Management",
  "Directeur de l’Information Médicale": "Departement Information Medicale",
  "Directeur de Production": "Executive Management",
  "Directeur de Programmes Immobiliers": "Real Estate",
  "Directeur de Projet": "Innovation",
  "Directeur des Achats": "Procurement",
  "Directeur des Affaires Sociales": "HR",
  "Directeur de service": "Departement Information Medicale",
  "Directeur des Exportations": "Executive Management",
  "Directeur des Investissements": "Real Estate",
  "Directeur de Site": "Executive Management",
  "Directeur des Opérations": "Executive Management",
  "Directeur Développement Durable": "Facilities",
  "Directeur Développement Immobilier": "Real Estate",
  "Directeur Diversité/Handicap": "HR",
  "Directeur du Personnel": "HR",
  "Directeur ESG": "Facilities",
  "Directeur Financier": "Finance",
  "Directeur Fiscal": "Finance",
  "Directeur Formation Adjoint": "HR",
  "Directeur Général": "Executive Management",
  "Directeur Général Adjoint": "Executive Management",
  "Directeur Général des Services": "Executive Management",
  "Directeur Hygiène et Sécurité": "HR",
  "Directeur Immobilier": "Real Estate",
  "Directeur Informatique": "Telecom & IT",
  "Directeur Innovation": "Innovation",
  "Directeur International": "Executive Management",
  "Directeur Juridique": "Legal",
  "Directeur Logistique": "Operations",
  "Directeur Marchés Publics": "Service Public",
  "Directeur Marketing": "Sales & Marketing",
  "Directeur Médiathèque": "Departement Information Medicale",
  "Directeur Medical": "Departement Information Medicale",
  "Directeur Prévention": "HR",
  "Directeur Qualité": "Executive Management",
  "Directeur Recherche Développement": "Innovation",
  "Directeur Régional": "Sales & Marketing",
  "Directeur Ressources Humaines": "HR",
  "Directeur Risques Engagement": "Legal",
  "Directeur RSE": "Facilities",
  "Directeur Scientifique": "Innovation",
  "Directeur Service Informatique": "Telecom & IT",
  "Directeur Services Généraux": "Facilities",
  "Directeur Services Techniques": "Facilities",
  "Directeur Stratégie": "Executive Management",
  "Directeur Technique": "Innovation",
  "DSI Adjoint": "Telecom & IT",
  "Elu Affaires sociales": "Service Public",
  "Fiscalité": "Finance",
  "Gérant": "Executive Management",
  "Gestionnaire Carrière": "HR",
  "Gestionnaire Cellule Marchés": "Legal",
  "Gestionnaire Chômage": "Service Public",
  "Gestionnaire de Parc": "Procurement",
  "Gestionnaire Financier": "Finance",
  "Gestionnaire Paie": "HR",
  "Gestionnaire Prévention": "HR",
  "Gestionnaire Retraite": "Service Public",
  "Gestionnaire RH": "HR",
  "Informaticien": "Telecom & IT",
  "Ingénieur": "Innovation",
  "Ingénieur Sécurité": "HR",
  "Investment Fund Manager": "Real Estate",
  "Juriste": "Legal",
  "Maire": "Service Public",
  "Maire Adjoint": "Service Public",
  "Médecin": "Departement Information Medicale",
  "Membre du Comité de Direction": "Executive Management",
  "Président": "Executive Management",
  "Président Conseil Surveillance": "Executive Management",
  "Président Directeur Général": "Executive Management",
  "Président du Conseil d'Administration": "Executive Management",
  "Président du Directoire": "Executive Management",
  "Property Manager": "Real Estate",
  "Responsable BE": "Innovation",
  "Responsable Carrière": "HR",
  "Responsable Cellule Marchés": "Legal",
  "Responsable Chômage": "Service Public",
  "Responsable Contrôle de gestion": "Finance",
  "Responsable CSP Paie": "HR",
  "Responsable d'Exploitation": "Operations",
  "Responsable de la Formation": "HR",
  "Responsable des Achats": "Procurement",
  "Responsable de Santé": "HR",
  "Responsable du Contentieux": "Finance",
  "Responsable du Personnel": "HR",
  "Responsable ESG": "Facilities",
  "Responsable Financier": "Finance",
  "Responsable Informatique": "Telecom & IT",
  "Responsable Infrastructures Réseaux": "Telecom & IT",
  "Responsable Logistique": "Operations",
  "Responsable Marketing Communication": "Sales & Marketing",
  "Responsable Paie": "HR",
  "Responsable Pôle Immobilier": "Real Estate",
  "Responsable Portfolio": "Real Estate",
  "Responsable Prévention": "HR",
  "Responsable Propriété Intellectuelle": "Legal",
  "Responsable Qualité": "Operations",
  "Responsable Qualité Vie Travail": "HR",
  "Responsable R et D": "Innovation",
  "Responsable RH": "HR",
  "Responsable RPS": "HR",
  "Responsable RSE": "Facilities",
  "Responsable section": "Service Public",
  "Responsable Services Généraux": "Facilities",
  "Responsable SIRH": "HR",
  "Responsable Technique": "Innovation",
  "Secrétaire de Direction": "Executive Management",
  "Secrétaire Général": "Executive Management",
  "Secrétaire Général Adjoint": "Executive Management",
  "Secrétaire Médicale": "Departement Information Medicale",
  "Trésorier": "Finance",
  "Vice-Président": "Executive Management"
};

// Mots-clés par département, pour trouver « DRH » en tapant « ressources humaines ».
export var DEPT_SYNONYMS = {
  "Executive Management": "direction generale dirigeant comite executif ceo pdg dg president directeur general",
  "HR": "ressources humaines rh drh recrutement formation paie personnel social",
  "Sales & Marketing": "ventes vente commercial marketing communication comm digital",
  "Telecom & IT": "informatique si dsi numerique digital systemes information tech telecom reseau",
  "Procurement": "achats achat approvisionnement acheteur procurement supply",
  "Legal": "juridique droit legal avocat conformite compliance contrats",
  "Finance": "finance financier comptabilite comptable tresorerie controle gestion audit fiscal",
  "Operations": "operations production logistique exploitation supply chain qualite",
  "Real Estate": "immobilier foncier patrimoine real estate",
  "Facilities": "services generaux moyens generaux facilities maintenance environnement rse esg developpement durable",
  "Innovation": "innovation recherche developpement rd",
  "Departement Information Medicale": "information medicale dim sante hospitalier",
  "Service Public": "service public secteur public administration collectivite mairie elu"
};
